<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE offers [
  <!ELEMENT offers (offer+)>
  <!ELEMENT offer (id,title,total,reference)>
  <!ELEMENT id (#PCDATA)>
  <!ELEMENT title (#PCDATA)>
  <!ELEMENT total (#PCDATA)>
  <!ELEMENT reference (#PCDATA)>
]>
<offers>
  <offer>
    <id>73SDGA</id>
    <title>Partial CoSum Item#92623</title>
    <total>272</total>
    <reference>HS0282</reference>
  </offer>
  <offer>
    <id>84SDZZ</id>
    <title>Custom Xbsg Item#3668</title>
    <total>5</total>
    <reference>ZD8356</reference>
  </offer>
</offers>
